POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "jeffrey",
    "password": "abcd1234",
    "email": "jeffrey@gmail.com"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "password": "abcd1234",
    "email": "jeffrey@gmail.com"
}
